### ISSUE TITLE
Requirements progress

### ISSUE THREAD

**Issue by Titouan-Loeb** [gabriel654165/RacingPod-StarWars#4]
## Main Menu / 1

- [ ] Functionnal main menu / 0.25
- [ ] Settings (keyboard, graphics, sound) / 0.25
- [ ] Design that aligns with the artistic direction of the game / 0.5

### Linked Issues
- [ ] #1 

## Playable Character / 1

- [ ] Good feedback on character/vehicle control

## Splash Screen & Credits (endgame) / 1

- [ ] You must display a splash screen before the menu / 0.5
- [ ] You must display a credits or an end cinematic instead of a win screen « gg return to main menu » / 0.5
- [ ] It must have the same artistic direction as the whole game

## Fully playable with a controller / 1

- [ ] You must have a game fully playable with a gamepad controller AND keyboard/mouse (for the menu as well) / 1

### Linked Issues
- [ ] #5 

## Main mechanic (course game) / 1

- [ ] You must use the main mechanic of the module « a course » in your gameplay. It can be used the way you want.

## Menu Pause in Game/ 1

- [ ] Functionnal menu pause / 0.25
- [ ] Settings (keyboard, graphics, sound) / 0.25
- [ ] Design that aligns with the artistic direction of the game / 0.5
- [ ] If you press escape or start (gamepad controller) it closes the menu.

### Linked Issues
- [ ] #2
