### ISSUE TITLE
Advanced requirements progress

### ISSUE THREAD

**Issue by Titouan-Loeb** [gabriel654165/RacingPod-StarWars#6]
## Menu Polish / 1

- [ ] Hover/Clicked effect of the buttons / 0.5
- [ ] Logic and fluid user experience / 0.5

### Linked Issues
- [ ] #1 

## Playable character/vehicle / 1

- [ ] No glitch regarding the character/vehicle / 0.5
- [ ] User experience on the movement and control of the character/vehicle / 0.5

### Linked Issues
- [ ] #5 

## Comprehension of the mechanics / 3
- [ ] Having a tutoriel or not, the main mechanics must be understanble quickly by the player / 1
- [ ] Using VFX AND SFX to help the player to understand the mechanics / 1
- [ ] The user experience on theses mechanics must be well implemented and design / 1
(Floating text with roboto font is not well implemented and design..)

## Environment and scenery / 3
- [ ] You cannot use a map that you got from a marketplace or somewhere else. You must have designed the map.
- [ ] You cannot use an existing map. Everything must be done by you.
- [ ] The map must use assets / 0.5
- [ ] The map must use the artistic direction of the game / 0.5
- [ ] If you do landscape, you cannot create huge ugly mountains. Try to make something good looking.
- [ ] The player must understand where he should go, the level design should be made regarding the main goal of your game / 1
- [ ] The level should not be empty / 1

## Main Mechanics : COURSE / 2

- [ ] Having a timer system that shows us our time between checkpoints / 0.5
- [ ] Speed feeling must be juicy / 0.5
- [ ] Add rivals to play with (with a ladderboard) / 0.5
- [ ] The feedbaks/User experience must be well implemented / 0.5

## Game feeling / 4

- [ ] Does the player understand the mechanics ? Are they great ? Good looking ? Easy to understand ? Using a tutoriel or not ? With VFX and SFX ?
- [ ] You need to make sure that your game is cool when you are playing to it. Make sure to test a lot your game and be sure that everthing works fine. It works fine on my computer is not an valid excuse.
